name: Build

on: [push, workflow_dispatch]

jobs:
  fetch-boost:
    runs-on: ubuntu-20.04
    steps:
    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v2
      with:
        path: boost.zip
        key: boost
    - name: Checkout Boost
      uses: actions/checkout@v2
      with:
        repository: boostorg/boost
        ref: dcea40897111fb7c4b92b17455e177d6d2bf735c
        submodules: recursive
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Build Boost
      run: |
        ./bootstrap.sh
        ./b2 headers
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Archive
      run: zip -r9 boost.zip boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: dep-boost
        path: boost.zip
  build-linux:
    runs-on: ubuntu-20.04
    needs: fetch-boost
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Boost
      uses: actions/download-artifact@v2
      with:
        name: dep-boost
    - name: Expand Boost
      run:  unzip boost.zip
    - name: Setup CUDA
      uses: Jimver/cuda-toolkit@v0.2.4
      with:
        cuda: 11.2.2
    - name: Configure
      run: |
        mkdir build
        cmake -S. -Bbuild -DBoost_INCLUDE_DIRS=`pwd` -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: make
      working-directory: build
    - name: Strip
      run: strip -s libEEDI2CUDA.so
      working-directory: build
    - name: Upload
      uses: actions/upload-artifact@v2
      with:
        name: EEDI2CUDA-Linux
        path: build/libEEDI2CUDA.so
